rotAngle = [0,-135,135]
chanWidth = 39
junction = {y=366,x=209}
bbox = {height=680,width=418,y=200,x=16}
tmplBBox = {height=20,width=20,y=211,x=10}

chanBBox = [
{height=366,width=39,y=200,x=190},
{height=209,width=209,y=566,x=0},
{height=209,width=209,y=566,x=209},
]

[[rotChanBBox]]
height = 0
width = 0
y = 0
x = 0
[[rotChanBBox]]
height = 295
width = 39
y = 0
x = 128
[[rotChanBBox]]
height = 295
width = 39
y = 0
x = 128
