rotAngle = [135,-135,0]
chanWidth = 100
junction = {y=200,x=200}
bbox = {height=400,width=600,y=0,x=0}
tmplBBox = {height=55,width=55,y=156,x=5}

chanBBox = [
{height=200,width=300,y=200,x=200},
{height=200,width=300,y=200,x=0},
{height=200,width=100,y=0,x=150},
]

[[rotChanBBox]]
height = 282
width = 100
y = 0
x = 141
[[rotChanBBox]]
height = 282
width = 100
y = 0
x = 141
[[rotChanBBox]]
height = 0
width = 0
y = 0
x = 0

