chWidth = 56
numChs = 3
bgSubHistory = 500
bgSubThres = 50.0

chROIs = [
{height=668,width=56,angle=0,chHeight=628.0,y=50,x=612},
{height=56,width=668,angle=90,chHeight=66.0,y=50,x=0},
{height=56,width=668,angle=-90,chHeight=68.0,y=50,x=612},
]

