rotAngle = [0,-90,90]
chanWidth = 31
junction = {y=441,x=215}
bbox = {height=480,width=430,y=0,x=16}
tmplBBox = {height=20,width=20,y=54,x=5}

chanBBox = [
{height=441,width=31,y=0,x=200},
{height=31,width=215,y=426,x=0},
{height=31,width=215,y=426,x=215},
]

[[rotChanBBox]]
height = 0
width = 0
y = 0
x = 0
[[rotChanBBox]]
height = 267
width = 31
y = 0
x = 118
[[rotChanBBox]]
height = 267
width = 31
y = 0
x = 118

