rotAngle = [0,-135,135]
chanWidth = 31
junction = {y=566,x=189}
bbox = {height=880,width=378,y=0,x=16}
tmplBBox = {height=20,width=20,y=231,x=5}

chanBBox = [
{height=566,width=31,y=0,x=174},
{height=189,width=189,y=566,x=0},
{height=189,width=189,y=566,x=189},
]

[[rotChanBBox]]
height = 0
width = 0
y = 0
x = 0
[[rotChanBBox]]
height = 267
width = 31
y = 0
x = 118
[[rotChanBBox]]
height = 267
width = 31
y = 0
x = 118

