chWidth = 56
numChs = 3
bgSubHistory = 500
bgSubThres = 60.0

chROIs = [
{height=752,width=56,angle=0,chHeight=628.0,y=128,x=426},
{height=56,width=456,angle=90,chHeight=66.0,y=100,x=0},
{height=56,width=433,angle=-90,chHeight=68.0,y=100,x=455},
]

