rotAngle = [135,-135,0]
chanWidth = 39
junction = {y=227,x=160}
bbox = {height=402,width=320,y=51,x=164}
tmplBBox = {height=30,width=30,y=0,x=0}

chanBBox = [
{height=160,width=160,y=227,x=160},
{height=160,width=160,y=227,x=0},
{height=227,width=39,y=0,x=141},
]

[[rotChanBBox]]
height = 226
width = 39
y = 0
x = 93
[[rotChanBBox]]
height = 226
width = 39
y = 0
x = 93
[[rotChanBBox]]
height = 0
width = 0
y = 0
x = 0

