chWidth = 38
numChs = 3
bgSubHistory = 500
bgSubThres = 16.0

chROIs = [
{height=646,width=38,angle=180,chHeight=628.0,y=234,x=432},
{height=38,width=470,angle=-90,chHeight=66.0,y=233,x=0},
{height=38,width=456,angle=90,chHeight=68.0,y=233,x=432},
]

