chWidth = 56
numChs = 3
bgSubHistory = 500
bgSubThres = 60.0

chROIs = [
{height=365,width=50,angle=0,chHeight=628.0,y=115,x=300},
{height=50,width=325,angle=90,chHeight=66.0,y=90,x=0},
{height=50,width=316,angle=-90,chHeight=68.0,y=90,x=324},
]
